import localFont from "next/font/local";
import "./globals.css";

const Inter = localFont({
  src: "./fonts/Inter.ttf",
  variable: "--font-inter",
  weight: "100 900",
});


export const metadata = {
  title: "XWIFTRX Ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Inter} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
